//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAbdomenInfo
    {
        public int intAbdomenInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isAbnormalMass { get; set; }
        public bool isPainful { get; set; }
        public bool isBloated { get; set; }
        public bool isEnlarged { get; set; }
        public bool isFluid { get; set; }
        public bool isHernia { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
