//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDepartment
    {
        public TDepartment()
        {
            this.TEmployees = new HashSet<TEmployee>();
        }
    
        public int intDepartmentID { get; set; }
        public string strDepartment { get; set; }
    
        public virtual ICollection<TEmployee> TEmployees { get; set; }
    }
}
