//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEyeStatusInfo
    {
        public int intEyeStatusInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isDischarge { get; set; }
        public bool isInfection { get; set; }
        public bool isSclerosisLeft { get; set; }
        public bool isSclerosisRight { get; set; }
        public bool isCataractLeft { get; set; }
        public bool isCataractRight { get; set; }
        public bool isInflamed { get; set; }
        public bool isEyelidTumor { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
