//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGIInfo
    {
        public int intGIInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isExcessiveGas { get; set; }
        public bool isParasites { get; set; }
        public bool isAbnormalFeces { get; set; }
        public bool isAnorexia { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
