//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLungInfo
    {
        public int intLungInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isBreathingDifficulty { get; set; }
        public bool isRapidRespiration { get; set; }
        public bool isTrachealPinchPositive { get; set; }
        public bool isTrachealPinchNegative { get; set; }
        public bool isCongestion { get; set; }
        public bool isAbnormalSound { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
