//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMedication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMedication()
        {
            this.TVisitMedications = new HashSet<TVisitMedication>();
        }
    
        public int intMedicationID { get; set; }
        public string strMedicationName { get; set; }
        public string strMedicationDesc { get; set; }
        public decimal dblCost { get; set; }
        public decimal dblPrice { get; set; }
        public string strNotes { get; set; }
        public int intQuantity { get; set; }
        public int intMethodID { get; set; }
    
        public virtual TMethod TMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisitMedication> TVisitMedications { get; set; }
    }
}
