//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMouthInfo
    {
        public int intMouthInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isTumor { get; set; }
        public bool isGingivitis { get; set; }
        public bool isPeriodontitis { get; set; }
        public bool isTartarBuildup { get; set; }
        public bool isLooseTeeth { get; set; }
        public bool isBiteOVerUnder { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
