//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMusculoskeletalInfo
    {
        public int intMusculoskeletalInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isJointProblems { get; set; }
        public bool isNailProblems { get; set; }
        public bool isLamenessLF { get; set; }
        public bool isLamenessRF { get; set; }
        public bool isLamenessLR { get; set; }
        public bool isLamenessRR { get; set; }
        public bool isLigaments { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
