//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNoseThroatInfo
    {
        public int intNoseThroatInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isLargeLymphNodes { get; set; }
        public bool isInflamedThroat { get; set; }
        public bool isNasalDishcharge { get; set; }
        public bool isInflamedTonsils { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
