//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public class TPetImage
    {
        public int intPetImageID { get; set; }
        public string strFileName { get; set; }
        public string strContentType { get; set; }
        public byte[] imgContent { get; set; }
        public string strFileType { get; set; }
        public int intPetID { get; set; }
    
        public virtual TPet TPet { get; set; }
        public List<TPetImage> PetImages { get; internal set; }
        //      public virtual ICollection<TP> Files { get; set; }


        public string BytesBase64 {
            get {
                try {
                    if (imgContent.Length > 0) { return Convert.ToBase64String(imgContent); }
                    return string.Empty;
                }
                catch (Exception ex) {
                    throw new Exception(ex.Message);
                }
            }
        }

    }
}
