//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRole
    {
        public TRole()
        {
            this.TUserRoleMappings = new HashSet<TUserRoleMapping>();
            this.TUsers = new HashSet<TUser>();
        }
    
        public int intRoleID { get; set; }
        public string strRole { get; set; }
    
        public virtual ICollection<TUserRoleMapping> TUserRoleMappings { get; set; }
        public virtual ICollection<TUser> TUsers { get; set; }
    }
}
