//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TService()
        {
            this.TVisitServices = new HashSet<TVisitService>();
        }
    
        public int intServiceID { get; set; }
        public string strServiceDesc { get; set; }
        public int intServiceTypeID { get; set; }
        public decimal dblPrice { get; set; }
    
        public virtual TServiceType TServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisitService> TVisitServices { get; set; }
    }
}
