//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSkinInfo
    {
        public int intSkinInfoID { get; set; }
        public bool isNormal { get; set; }
        public bool isScaly { get; set; }
        public bool isInfected { get; set; }
        public bool isMatted { get; set; }
        public bool isSkinScrape { get; set; }
        public bool isPruritus { get; set; }
        public bool isHairLoss { get; set; }
        public bool isMass { get; set; }
        public bool isParasites { get; set; }
        public int intHealthExamID { get; set; }
    
        public virtual THealthExam THealthExam { get; set; }
    }
}
