//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TState
    {
        public TState()
        {
            this.TOwners = new HashSet<TOwner>();
        }
    
        public int intStateID { get; set; }
        public string strStateCode { get; set; }
        public string strStateName { get; set; }
    
        public virtual ICollection<TOwner> TOwners { get; set; }
    }
}
