//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUser
    {
        public TUser()
        {
            this.TUserRoleMappings = new HashSet<TUserRoleMapping>();
        }
    
        public int intUserID { get; set; }
        public string strUserName { get; set; }
        public string strPassword { get; set; }
        public int intRoleID { get; set; }
    
        public virtual TRole TRole { get; set; }
        public virtual ICollection<TUserRoleMapping> TUserRoleMappings { get; set; }
    }
}
