//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUserRoleMapping
    {
        public int intUserRoleID { get; set; }
        public int intUserID { get; set; }
        public int intRoleID { get; set; }
    
        public virtual TRole TRole { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
