//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVisitEmployee
    {
        public int intVisitEmployeeID { get; set; }
        public int intVisitID { get; set; }
        public int intEmployeeID { get; set; }
    
        public virtual TEmployee TEmployee { get; set; }
        public virtual TVisit TVisit { get; set; }
    }
}
