//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVisit
    {
        public int intVisitID { get; set; }
        public int intPetID { get; set; }
        public int intVisitReasonID { get; set; }
        public System.DateTime dtmDateOfVist { get; set; }
    
        public virtual TVisitReason TVisitReason { get; set; }
    }
}
