//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVisitMedication
    {
        public int intVisitMedicationID { get; set; }
        public int intVisitID { get; set; }
        public int intMedicationID { get; set; }
        public System.DateTime dtmDatePrescribed { get; set; }
        public int intQuantity { get; set; }
    }
}
