//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVisitReason
    {
        public TVisitReason()
        {
            this.TVisits = new HashSet<TVisit>();
        }
    
        public int intVisitReasonID { get; set; }
        public string strVisitReason { get; set; }
    
        public virtual ICollection<TVisit> TVisits { get; set; }
    }
}
