//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVisit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVisit()
        {
            this.TVisitEmployees = new HashSet<TVisitEmployee>();
            this.TVisitMedications = new HashSet<TVisitMedication>();
            this.TVisitServices = new HashSet<TVisitService>();
        }
    
        public int intVisitID { get; set; }
        public int intPetID { get; set; }
        public int intVisitReasonID { get; set; }
        public System.DateTime dtmDateOfVist { get; set; }
    
        public virtual TPet TPet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisitEmployee> TVisitEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisitMedication> TVisitMedications { get; set; }
        public virtual TVisitReason TVisitReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVisitService> TVisitServices { get; set; }
    }
}
